services:
  tailscale:
    image: tailscale/tailscale${TAILSCALE_SHA:-${TAILSCALE_TAG:?}}
    container_name: ${COMPOSE_PROJECT_NAME}-tailscale
    hostname: ${TAILSCALE_HOSTNAME:-${COMPOSE_PROJECT_NAME}}
    cap_add:
      - net_admin
      - sys_module
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file:
      - common.env
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
    volumes:
      - ./tmp:/tmp
    healthcheck:
      test: wget -q --tries=1 --spider http://127.0.0.1:9002/healthz || exit 1
      start_period: 20s
      interval: 20s
      timeout: 10s
      retries: 2
