services:
  tailscale:
    image: tailscale/tailscale:latest
    extends:
      file: common.yaml
      service: tailscale
    env_file:
      - develop.env
    volumes:
      - ./data:/var/lib/tailscale
